name: Build caller workflow

on:
    push:
        branches: [ "main"]
    pull_request:
        branches: [ "main"]

jobs:
    caller-build:
              uses: iiakovleva-l/ci-cd-workflows/.github/workflows/build-maven.yml@main
              with:
                java-version: '17'
                maven-goals: 'clean package'
                
      
  